#!/usr/bin/env python3
"""HCP-001 Z4 — durable synthetic control, two distinct assertions.

A1: the family GENERATED by the j=|X∩U| partition equals the brute-force
    family exactly (set equality of frozensets).
A2: the partition formula's scalar count equals the cardinality of that family.

A1 is a set comparison; A2 is a scalar comparison. The earlier writeup
conflated them — only A2 was actually being run, because the counting routine
produced no family to compare. This version generates the family.

The 200 instances are serialized canonically and hashed, so the control is
replayable (standard JSONL, one LF per record) without depending on CPython's random.sample stream.
"""
from itertools import combinations
from math import comb
import hashlib
import json
import platform
import random
import time


def partition_generate(cons, universe):
    """Generate the hitting-set family via the j-partition."""
    U = sorted(set().union(*cons))
    O = [x for x in universe if x not in set(U)]
    n = len(cons)
    full = (1 << n) - 1
    hit = {}
    for j in U:
        m = 0
        for i, F in enumerate(cons):
            if j in F:
                m |= 1 << i
        hit[j] = m
    fam = set()
    for a in U:
        if hit[a] == full:
            for extra in combinations(O, 2):
                fam.add(frozenset((a,) + extra))
    for a, b in combinations(U, 2):
        if hit[a] | hit[b] == full:
            for extra in O:
                fam.add(frozenset((a, b, extra)))
    for a, b, c in combinations(U, 3):
        if hit[a] | hit[b] | hit[c] == full:
            fam.add(frozenset((a, b, c)))
    return fam


def partition_count(cons, universe):
    """Scalar count via the closed form."""
    U = sorted(set().union(*cons))
    O = len(universe) - len(U)
    n = len(cons)
    full = (1 << n) - 1
    hm = []
    for j in U:
        m = 0
        for i, F in enumerate(cons):
            if j in F:
                m |= 1 << i
        hm.append(m)
    u = len(hm)
    B1 = B2 = B3 = 0
    for a in range(u):
        ha = hm[a]
        if ha == full:
            B1 += 1
        for b in range(a + 1, u):
            hab = ha | hm[b]
            if hab == full:
                B2 += 1
            for c in range(b + 1, u):
                if hab | hm[c] == full:
                    B3 += 1
    return B1 * comb(O, 2) + B2 * O + B3


def brute(cons, universe):
    return {frozenset(X) for X in combinations(sorted(universe), 3)
            if all(set(X) & F for F in cons)}


t0 = time.perf_counter()
rng = random.Random(20260826)
instances, a1_ok, a2_ok = [], 0, 0
for _ in range(200):
    usz = rng.randint(8, 16)
    universe = list(range(usz))
    cons = []
    for _ in range(rng.randint(1, 5)):
        k = rng.randint(2, min(5, usz))
        cons.append(frozenset(rng.sample(universe, k)))
    cons = list(dict.fromkeys(cons))
    instances.append({"universe_size": usz,
                      "constraints": sorted(sorted(F) for F in cons)})
    fam_p = partition_generate(cons, universe)
    fam_b = brute(cons, universe)
    if fam_p == fam_b:
        a1_ok += 1
    if partition_count(cons, universe) == len(fam_p):
        a2_ok += 1

payload = "".join(
    json.dumps(inst, separators=(",", ":"), sort_keys=True) + "\n" for inst in instances)
sha = hashlib.sha256(payload.encode("utf-8")).hexdigest()

print(f"python={platform.python_version()} platform={platform.platform()}")
print(f"instances=200")
print(f"A1_family_equality_passed={a1_ok}/200")
print(f"A2_scalar_equals_family_cardinality_passed={a2_ok}/200")
print(f"instances_sha256={sha}")
print(f"instances_payload_bytes={len(payload.encode('utf-8'))}")
print(f"runtime_seconds={time.perf_counter()-t0:.2f}")
